### ISSUE TITLE
未登陆时进去http://vue3-admin.newbee.ltd 会出现渲染不是登陆页的内容 

### ISSUE THREAD

**Issue by zhouye0211** [newbee-ltd/vue3-admin#2]
1、从未登录的浏览器进入 http://vue3-admin.newbee.ltd ，出现先渲染内容的页面才会出现注册登录页

2、在登录页点浏览器按钮后退也是出现系统介绍页
![image](https://user-images.githubusercontent.com/32477246/112920415-7d868d00-913b-11eb-8f49-f3ea5f6133b3.png)

**Comment by newbee-mall** [comment]
因为这个页面不需要登录认证。
