### ISSUE TITLE
vite.config.js中proxy未生效

### ISSUE THREAD

**Issue by ARTAvrilLavigne** [newbee-ltd/vue3-admin#20]
请问yarn run dev启动后，首页登录接口没有被代理到后台路径和端口上，是怎么回事呢？端口和路径没有改为代理的后台路径
![image](https://user-images.githubusercontent.com/30069579/143451060-8da150a2-61cf-4e37-aec8-33dcebd42b63.png)
![image](https://user-images.githubusercontent.com/30069579/143450907-791f4fd9-69d2-4fca-b1d8-595e7e22ed20.png)
![image](https://user-images.githubusercontent.com/30069579/143450930-75239e86-581d-477a-8293-3aa89af85f3f.png)

**Comment by ZHENFENG13** [comment]
先自测 接口是不是通的，再把前端项目内的 /api 换成服务端抛出的接口地址

**Comment by ARTAvrilLavigne** [comment]
> 我刚刚将后台服务器启动了，发现是能访问进后台的。但是奇怪的是前台这个URL不应该显示的是代理后访问后台的URL么，比如这个登录接口，localhost:8080/api/adminUser/login，界面点击请求后(居然能进入后台，说明应该代理上了)，但F12此时并不是显示localhost:9527/manage-api/v1/adminUser/login，请教一下这是啥原因呢
<img width="1514" alt="微信图片_20211126144307" src="https://user-images.githubusercontent.com/30069579/143538543-b1a62eb3-153d-45be-8b5b-fbf0f8f94240.png">

**Comment by Nick930826** [comment]
@ARTAvrilLavigne 通过proxy 代理接口，是在内部做了代理了，不会直接体现在控制台上。控制台上的地址，是你的真实请求地址。

**Comment by ARTAvrilLavigne** [comment]
好的，谢谢指导！我明白了哈
