### ISSUE TITLE
控制台输出信息的位置总是为  instrument.ts:130 ,而且点进去，这文件并不知道在那里，请问如何获取当前页面输出信息的位置呢

### ISSUE THREAD

**Issue by 15735517450** [newbee-ltd/vue3-admin#21]

**Comment by Nick930826** [comment]
需要开启开发模式的souce-map

**Comment by 15735517450** [comment]
这个项目打包工具是vite，请问下如何开启呢

**Comment by Nick930826** [comment]
@15735517450 检查后发现，是sentry插件导致的，前往main.js，隐藏掉Sentry.init方法，重启项目试试。这个插件是检测生产环境下错误监控的插件，也可以通过环境变量去判断是否隐藏Sentry.init方法。

**Comment by 15735517450** [comment]
嗯嗯，大佬，问题已经解决了，谢谢大佬
