### ISSUE TITLE
XSS vulnerability exists in background editor

### ISSUE THREAD

**Issue by L0ading-x** [newbee-ltd/vue3-admin#22]
XSS vulnerability exists in background editor
You can write xsspayLoad when adding items
![image](https://user-images.githubusercontent.com/55682875/149462804-66337f1a-2f9d-4b17-9739-cdca90e009fb.png)
![image](https://user-images.githubusercontent.com/55682875/149462854-e14b6a00-3ff2-41a5-80cd-fe57e914a4c1.png)

**Comment by L0ading-x** [comment]
Why put up the bug and then do not reply but secretly fix it

**Comment by 0oHalao0** [comment]
> Why put up the bug and then do not reply but secretly fix it

Maybe he found out by themselves?

**Comment by L0ading-x** [comment]
maybe!

**Comment by Nick930826** [comment]
> maybe!

we did nothing
