### ISSUE TITLE
indexConfig 后台存在几个问题，首页配置模块删除提示未知异常等

### ISSUE THREAD

**Issue by liubangde** [newbee-ltd/vue3-admin#23]
实际删除接口为：DELETE http://localhost:8019/manage-api/v1/indexConfigs
而非
![image](https://user-images.githubusercontent.com/73807441/152089955-eba93f50-6665-42af-a8b1-a62d1cae609c.png)

修改后应为
![image](https://user-images.githubusercontent.com/73807441/152090002-85071254-aa78-47db-b92a-070d21c05ae5.png)

好像还有添加，修改时提示商品已存在，应该是传参问题。

**Comment by jin-pin-mei-le** [comment]
最近在学习java，我想参与这个项目的开发。

**Comment by ZHENFENG13** [comment]
> 最近在学习java，我想参与这个项目的开发。

可以啊，API项目的开发语言就是Java，可以学起来。
