### ISSUE TITLE
表单验证

### ISSUE THREAD

**Issue by huxianc** [newbee-ltd/vue3-admin#3]
添加商品页面，所有的表单验证都是通过行内添加`required`实现的，这样的话数据里面自定义的`rule`就无效了，是故意这么设计的吗？
其次 ，在 我们之前的项目中，`rule`可以设置成非响应式，它会自动通过`trigger`触发

**Comment by huxianc** [comment]
商品主图那个上传图片样式建议加一个`overflow:hidden;`，现在上传图片超出也会显示

**Comment by newbee-mall** [comment]
感谢建议，我看一下哈。
