### ISSUE TITLE
测试账号不能登陆

### ISSUE THREAD

**Issue by tomrets** [newbee-ltd/vue3-admin#41]
测试账号的话 会报502

**Comment by Nick930826** [comment]
收到，尽快修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 晚上6:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [newbee-ltd/vue3-admin] 测试账号不能登陆 (Issue #41)




 
测试账号的话 会报502
