### ISSUE TITLE
傻逼，刷尼玛的 star，卖课滚一边去

### ISSUE THREAD

**Issue by xiangshu233** [newbee-ltd/vue3-admin#42]

**Comment by Nick930826** [comment]
你不适合做开发，穷逼。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月1日(周三) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [newbee-ltd/vue3-admin] 傻逼，刷尼玛的 star，卖课滚一边去 (Issue #42)

**Comment by ZHENFENG13** [comment]
@xiangshu233 你可以活得阳光点儿

**Comment by xiangshu233** [comment]
@ZHENFENG13 我还是把恶意强加给别人舒服点
