### ISSUE TITLE
首页配置，添加商品时添加完成后，会显示校验规则显示的问题

### ISSUE THREAD

**Issue by sean-lgt** [newbee-ltd/vue3-admin#7]

**Comment by ZHENFENG13** [comment]
好的，我看一下。

**Comment by ZHENFENG13** [comment]
没发现什么问题，有具体的图片嘛？如果没有的话我就关闭了。

**Comment by sean-lgt** [comment]
好的&nbsp; 我这边再看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "newbee-ltd/vue3-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月30日(星期五) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [newbee-ltd/vue3-admin] 首页配置，添加商品时添加完成后，会显示校验规则显示的问题 (#7)





 
没发现什么问题，有具体的图片嘛？如果没有的话我就关闭了。
