### ISSUE TITLE
判断是否登录不考虑 token 失效？

### ISSUE THREAD

**Issue by xiaomlove** [newbee-ltd/vue3-admin#8]
[这里](https://github.com/newbee-ltd/vue3-admin/blob/main/src/App.vue#L106)，只判断 token 是否存在，如果失效了呢？怎么统一拦截跳转到登录页面？

**Comment by ZHENFENG13** [comment]
如果token不存在，一定是未登录的。

如果存在，这里只代表曾经登录过或者用户自己伪造的token，但是不代表token有效，此时带着这个token值去请求后端接口，又有两个逻辑路径：
1.token有效，则正常返回数据。
2.token无效，后端会返回一个错误码416或者419，当收到这两个错误码时，也会跳转到登录页面。

**Comment by xiaomlove** [comment]
是 [这里](https://github.com/newbee-ltd/vue3-admin/blob/main/src/utils/axios.js#L27) 的逻辑吧，这块明白了。感谢解惑。

**Comment by ZHENFENG13** [comment]
OK
