### ISSUE TITLE
是否展示左侧菜单的判断有 bug

### ISSUE THREAD

**Issue by xiaomlove** [newbee-ltd/vue3-admin#9]
[这里](https://github.com/newbee-ltd/vue3-admin/blob/main/src/App.vue#L112) 判断是否展示左侧菜单，在路由的 beforeEach 里边，感觉元素不止一项，会重复设定。而且，登录成功后退出，再点后退，这时会展示登录页面 + 左侧菜单。

**Comment by ZHENFENG13** [comment]
有截图吗？

**Comment by xiaomlove** [comment]
直接登录成功点退出，再点后退按钮就有了。
![image](https://user-images.githubusercontent.com/8530353/116665796-c5176780-a9cc-11eb-80ec-17730fec7285.png)

**Comment by ZHENFENG13** [comment]
已处理

**Comment by xiaomlove** [comment]
没有更新么？我看还是存在的。

**Comment by ZHENFENG13** [comment]
更新了

**Comment by xiaomlove** [comment]
修改并没有用。。。问题依然存在

**Comment by longlingwen** [comment]
IE11无法使用
